language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly

script:
  - rustup component add rustfmt
  - cargo fmt -- --check
  - cargo build --verbose
  - cargo test --verbose

deploy:
  - provider: script
    script: cargo publish --token ${CRATES_IO_TOKEN}

    on:
      tags: true
      branch: master
      condition: "$TRAVIS_RUST_VERSION = stable"
